const { chromium } = require('playwright');
const fs=require('fs'),path=require('path'),assert=require('assert');
(async()=>{
 const launch={headless:true}; if(process.env.CHROMIUM_EXECUTABLE){launch.executablePath=process.env.CHROMIUM_EXECUTABLE;launch.args=['--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--no-zygote','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'];} if(process.env.CHROMIUM_PACKAGE){const bundled=(await import(process.env.CHROMIUM_PACKAGE)).default;launch.executablePath=await bundled.executablePath();launch.args=bundled.args;} const browser=await chromium.launch(launch);const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const mock=`window.__rows=[];window.__session=null;window.supabase={createClient:()=>({
 auth:{getSession:async()=>({data:{session:window.__session}}),signInWithPassword:async()=>{window.__session={user:{id:'test-user',email:'test@example.invalid'}};return{data:{session:window.__session}}},signUp:async()=>{window.__session={user:{id:'test-user',email:'test@example.invalid'}};return{data:{session:window.__session}}},signOut:async()=>{window.__session=null;return{}},onAuthStateChange:()=>({})},
 rpc:async()=>({data:window.__destination||null}),
 from:()=>{let payload=null,id=null;const b={select:()=>b,order:()=>b,range:async()=>({data:window.__rows}),update:p=>{payload=p;return b},insert:p=>{payload=p;return b},eq:(_,v)=>{id=v;return b},single:async()=>{let row;if(id){row=window.__rows.find(r=>r.id===id);Object.assign(row,payload)}else{row={...payload,id:'test-row',public_url:location.origin+'/?q='+'a'.repeat(32),created_at:'2026-10-09T12:00:00Z'};window.__rows.push(row)}return{data:{...row}}}};return b}
})};`;
 await page.route('**/vendor/supabase.js',r=>r.fulfill({contentType:'application/javascript',body:mock}));
 await page.route('**/auth/v1/settings',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({mailer_autoconfirm:true,disable_signup:false})}));
 const out=path.resolve('docs');const results=[];const pass=s=>results.push(s);
 await page.goto('http://127.0.0.1:8765/');await page.locator('#auth-loading').waitFor({state:'hidden'});
 assert(await page.locator('#auth-screen').isVisible());assert.equal(await page.locator('meta[name=robots]').getAttribute('content'),'index,follow,max-image-preview:large');pass('Portada visible y meta robots pública');
 await page.screenshot({path:out+'/portada-desktop.png',fullPage:true,animations:'disabled'});
 await page.fill('#guest-link','https://example.com/catalogo');await page.click('#guest-form button');await page.locator('#guest-result').waitFor({state:'visible'});
 for(const [button,name] of [['#guest-png','prueba-qr.png'],['#guest-svg','prueba-qr.svg']]){const d=page.waitForEvent('download');await page.click(button);await(await d).saveAs(out+'/'+name);assert(fs.statSync(out+'/'+name).size>100);}
 pass('Generación QR sin cuenta y descarga real PNG/SVG');
 await page.click('#switch-auth');await page.fill('#signup-email','test@example.invalid');await page.fill('#signup-password','testonly123');await page.fill('#signup-confirm','mismatch123');await page.click('#signup-form button');assert((await page.textContent('#auth-message')).includes('no coinciden'));await page.fill('#signup-confirm','testonly123');await page.click('#signup-form button');await page.locator('#dashboard').waitFor({state:'visible'});pass('Registro simulado; validación confirmación y apertura panel');
 assert((await page.locator('meta[name=robots]').getAttribute('content')).includes('noindex'));pass('Panel autenticado marcado noindex');
 await page.click('#new-qr');await page.fill('#qr-name','Catálogo prueba');await page.fill('#qr-destination','https://example.com/a');await page.click('#save-qr');await page.locator('#detail').waitFor({state:'visible'});
 const permanent=await page.inputValue('#permanent-link');
 for(const button of ['#download-png','#download-svg']){const d=page.waitForEvent('download');await page.click(button);assert((await d).suggestedFilename().toLowerCase().includes('catalogo'));}
 await page.click('[data-close="detail"]');await page.getByRole('button',{name:'Editar',exact:true}).click();await page.fill('#qr-destination','https://example.com/b');await page.click('#save-qr');assert.equal(await page.locator('.destination').getAttribute('href'),'https://example.com/b');await page.getByRole('button',{name:'↓ QR',exact:true}).click();assert.equal(await page.inputValue('#permanent-link'),permanent);await page.click('[data-close="detail"]');pass('Crear QR dinámico, editar destino conservando URL y descargar PNG/SVG (Supabase simulado)');
 await page.getByRole('button',{name:'Pausar',exact:true}).click();assert.equal(await page.textContent('#stat-paused'),'1');await page.getByRole('button',{name:'Activar',exact:true}).click();assert.equal(await page.textContent('#stat-active'),'1');await page.fill('#search','no existe');assert.equal(await page.locator('.qr-card').count(),0);await page.fill('#search','Catálogo');assert.equal(await page.locator('.qr-card').count(),1);pass('Pausar, activar y buscar (Supabase simulado)');
 await page.click('#logout');await page.locator('#auth-screen').waitFor({state:'visible'});await page.fill('#email','test@example.invalid');await page.fill('#password','testonly123');await page.click('#login-form button');await page.locator('#dashboard').waitFor({state:'visible'});await page.click('#logout');pass('Inicio y cierre de sesión simulados');
 await page.goto('http://127.0.0.1:8765/?q=invalid');await page.waitForFunction(()=>document.getElementById('redirect-message').textContent.includes('no es válido'));assert((await page.locator('meta[name=robots]').getAttribute('content')).includes('noindex'));assert.equal(await page.locator('link[rel=canonical]').count(),0);assert.equal(await page.locator('#auth-screen').isVisible(),false);pass('QR inválido, noindex y pantalla de error');
 await page.goto('http://127.0.0.1:8765/?q='+'a'.repeat(32));await page.waitForFunction(()=>document.getElementById('redirect-title').textContent.includes('no está disponible'));pass('QR pausado/inexistente con RPC simulado');
 await page.addInitScript(()=>window.__destination='https://example.com/destino-final');await page.route('https://example.com/destino-final',r=>r.fulfill({body:'Destino de prueba'}));await page.goto('http://127.0.0.1:8765/?q='+'b'.repeat(32));await page.waitForURL('https://example.com/destino-final');pass('Redirección efectiva a destino devuelto por RPC simulado');
 const context=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});const mobile=await context.newPage();await mobile.goto('http://127.0.0.1:8765/');assert(await mobile.locator('#auth-screen').isVisible());await mobile.locator('summary').click();assert(await mobile.getByRole('link',{name:'Cómo crear un código QR para un enlace',exact:true}).isVisible());await mobile.screenshot({path:out+'/portada-mobile-sin-js.png',fullPage:true,animations:'disabled'});
 const metadata=JSON.parse(fs.readFileSync('docs/metadatos-y-palabras-clave.json'));
 for(const item of metadata){const pathname=new URL(item.url).pathname;const r=await mobile.goto('http://127.0.0.1:8765'+pathname);assert.equal(r.status(),200);assert.equal(await mobile.title(),item.title);assert.equal(await mobile.locator('link[rel=canonical]').getAttribute('href'),item.url);const dims=await mobile.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert(dims.scroll<=dims.width,pathname+' horizontal overflow');if(pathname!='/')assert.equal(await mobile.locator('h1').count(),1);}
 await mobile.screenshot({path:out+'/guia-mobile.png',fullPage:true,animations:'disabled'});pass('8 páginas HTTP 200 locales, títulos/canonical, lectura sin JS, sin desbordamiento a 390px');
 assert.deepEqual(errors,[]);pass('Sin errores JavaScript en los flujos ejecutados');
 fs.writeFileSync(out+'/pruebas-navegador.json',JSON.stringify({date:new Date().toISOString(),scope:'Local, Chromium. Supabase simulado; no verifica Auth/RLS/base de datos reales.',passed:results},null,2));console.log(results.join('\n'));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
